Do
msgbox("Get fucked")
msgbox("haha")
msgbox("i wont go away")
msgbox("give up")
msgbox("ok i guess...")
msgbox("...youre...")
msgbox("never gonna give this up?")
msgbox("still trying?")
msgbox("Press F to pay respect")
msgbox("ha pressing F does")
msgbox("NOTHING HAHAHA")
msgbox("you are an idiot")
msgbox("hahahaha haha ha haha haha ha ha")
msgbox("STOP IT!!")
msgbox(":)")
msgbox("alright")
msgbox("press ok or close the window to restart")
msgbox("ok here we go again")
loop